project_id            = "eastern-augury-477909-q6"
region                = "us-central1"
repository_name       = "cloud-run-terraform-scaling"
service_account_email = "162720148859-compute@developer.gserviceaccount.com"
environment           = "prod"
branch_pattern        = "^prod$"
